### ISSUE TITLE
Issue launching puppeteer.

### ISSUE THREAD

**Issue by justinmccormack** [KoryNunn/pee-dee-eff#6]
This module does not work with later versions of puppeteer (last known working version of puppeteer is v1.2 - March 2018).

The error is - 'return this._launcher.launch(options);
TypeError: Cannot read property '_launcher' of null'

This is caused by righto not sending through a 'this' context when applying the function.

**Comment by KoryNunn** [comment]
Thanks,

Fixed and published as 2.3.1

**Comment by justinmccormack** [comment]
Thanks Kory!

**Comment by KoryNunn** [comment]
Also I noticed you went to fork righto, i assume to support sending `this` through.

This is not a limitation of righto, but rather of the language, functions that use an un-bound `this` are not able to be passed around or used in a functional manner. There are many ways around this:

Assume an API: 
```js
function createMyThing(){
    var myThing = {
      foo: () => { return 1 },
      bar: () => { return this.foo() + 1 }
    }

    return myThing;
}
```
This will not work, because `this` is not bound to the function:

```js
var myThingBar = createMyThing().bar;

myThingBar(); // ERROR property foo does not exist on undefined!
```
## Solutions:

Avoid `this` in the library (IMO, the best option):

```js
function createMyThing(){
    var myThing = {};
    myThing.foo = () => { return 1 };
    myThing.bar = () => { return myThing.foo() + 1 };

    return myThing;
}

var myThingBar = createMyThing().bar;

myThingBar(); // Works
```

Bind context to the function in the library (the second best option):

```js
function createMyThing(){
    var myThing = {};
    myThing.foo = function(){ return 1 };
    myThing.bar = function(){ return this.foo() + 1 }.bind(myThing);
    return myThing;
}

var myThingBar = createMyThing().bar;

myThingBar(); // Works
```

Bind context to the function externally

```js
var myThing = createMyThing();
var myThingBar = myThing.bar.bind(myThing);

myThingBar(); // Works
```
Binding the context externally is really hard when you have a fluent API, for example:

```js
var doAllThings = foo().doThing().thenStuff().thenAnotherThing; // thenAnotherThing will lose context here.
```
Which is why I wrote https://github.com/KoryNunn/fluent-context

**Comment by justinmccormack** [comment]
Makes sense. Thanks Kory.

Justin
